web:
  upload-path: C:/OnlineTeaching_images
spring:
  mvc:
    static-path-pattern: /**
  application:
    name: Teacher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ECDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: '011006'
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    #配置服务管理nacos
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      #配置服务限流sentinel
    sentinel:
      transport:
        #sentinel服务默认端口，访问localhost:8080管理服务。
        dashboard: localhost:8080
  web:
    resources:
      static-locations: file:${web.upload-path},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  port: 8081
#使用sentinel要开放所有接口
management:
  endpoints:
    web:
      exposure:
        include: '*'
config:
  jwt:
    # 加密密钥
    secret: abcdefg12345678
    # token有效时长
    expire: 3600
    # header 名称
    header: Token

