server:
  port: 8082
spring:
  application:
    name: Student
  # 配置nacos管理服务。
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #sentinel服务默认端口，访问localhost:8080管理服务。
    sentinel:
      transport:
        dashboard: localhost:8080
#使用sentinel要开放所有接口
management:
  endpoints:
    web:
      exposure:
        include: '*'